#include "int_vector.h"

extern NAKED void init();

#define STACK_BOTTOM 0x20088000

void *vector_table[] __attribute((section(".vector_tbl"))) = {
  (void *)STACK_BOTTOM,
  (void *)init,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector,
  (void *)bad_vector
};
